name: Check

on: [push]

jobs:
  install-windows:
    runs-on: windows-latest

    steps:
      - name: Install
        run: |
          bitsadmin /TRANSFER DOTFILES https://raw.github.com/proudust/dotfiles/${{ github.sha }}/install.bat %TEMP%\install.bat
          %TEMP%\install.bat
        shell: cmd
        env:
          CHECKOUT_REF: ${{ github.sha }}
          SKIP_WINGET_CHECK: true

  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Install
        run: bash <(curl -sL raw.github.com/proudust/dotfiles/${{ github.sha }}/install.sh)
        env:
          CHECKOUT_REF: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Init
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" </dev/null
          /home/linuxbrew/.linuxbrew/bin/brew install shellcheck shfmt
      - name: shfmt
        run: /home/linuxbrew/.linuxbrew/bin/shfmt -d .
      - name: ShellCheck
        run: /home/linuxbrew/.linuxbrew/bin/shellcheck *.sh .bashrc
