name: Check

on: [push]

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Install
        run: bash <(curl -sL raw.github.com/proudust/dotfiles/${{ github.sha }}/install.sh)
        env:
          CHECKOUT_REF: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" </dev/null
          /home/linuxbrew/.linuxbrew/bin/brew install shellcheck shfmt
      - name: shfmt
        run: /home/linuxbrew/.linuxbrew/bin/shfmt -d .
      - name: ShellCheck
        run: /home/linuxbrew/.linuxbrew/bin/shellcheck *.sh .bashrc
